executor: KubernetesExecutor

airflow:
  # Global pip packages installed into all Airflow containers
  pipPackages:
    # Pin exactly; this version is just an example—match constraints for 3.0.2 + your Python
    - "apache-airflow-providers-cncf-kubernetes==10.0.0"


webserver:
  defaultUser:
    username: admin
    password: admin

webserverSecretKey: "c3633a19eb0140c052e787c498bffed6"

# Disable default PostgreSQL deployment
postgresql:
  enabled: false

# Use existing PostgreSQL instance
data:
  metadataConnection:
    user: "postgres"
    pass: "postgres"
    protocol: "postgresql"
    host: "postgres.crypto-gamble.svc.cluster.local"  # Kubernetes DNS for your Postgres service
    port: 5432
    db: "airflow"

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc
  mountPath: "/mnt/data/airflow-dags"


logs:
  persistence:
    enabled: true
    size: 10Gi






