apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: crypto-gamble
  labels:
    type: local
spec:
  storageClassName: standard
  # storageClassName: manual
  # storageClassName: 
  # persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # ✅ Must match PVC
  hostPath:
    path: "/mnt/data/airflow-dags"


# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: airflow-logs-pv
#   namespace: crypto-gamble
#   labels:
#     type: local
# spec:
#   storageClassName: standard # default
#   # storageClassName: manual
#   # persistentVolumeReclaimPolicy: Retain
#   volumeMode: Filesystem # default
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data/airflow-logs"
