apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: crypto-gamble
spec:
  selector:
    app: flink
    component: jobmanager
  type: NodePort  # Expose on a NodePort to allow access from outside
  ports:
    - name: taskmanager-rpc
      protocol: TCP
      port: 6122
      targetPort: 6122
    - name: jobmanager-rpc
      protocol: TCP
      port: 6123
      targetPort: 6123
    - name: blob
      protocol: TCP
      port: 6124
      targetPort: 6124
    - name: ui
      protocol: TCP
      port: 8081
      targetPort: 8081