apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: crypto-gamble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: 'true'
            - name: KAFKA_CLUSTERS_0_NAME
              value: "reddit-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.crypto-gamble.svc.cluster.local:9092"

