apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: crypto-gamble
spec:
  type: NodePort  #
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: kafka-ui
