apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-claim
  namespace: crypto-gamble
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgresql_data"