{
 "title": "MemeCoinMagic",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Distinct Posts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) as total_counts  FROM reddit_posts "
    }
   ]
  },
  {
   "title": "Distinct Meme Coins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  count(DISTINCT coin_name) as distinct_coin_names\nFROM reddit_posts "
    }
   ]
  },
  {
   "title": "Meme Coin Mentions (Trending Coins)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT coin_name, COUNT(*) AS mentions\nFROM reddit_posts\nWHERE coin_name IS NOT NULL\nGROUP BY coin_name\nORDER BY mentions DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Average Meme Coins Sentiment",
   "type": "timeseries",
   "description": "Average sentiment score for every given hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('hour', post_created_utc) AS hour_interval,\n    AVG(CAST(json_extract_path_text(sentiment::json, 'score') AS FLOAT)) AS avg_sentiment\nFROM reddit_posts\nWHERE coin_name IS NOT NULL\nGROUP BY hour_interval\nORDER BY avg_sentiment DESC;\n"
    }
   ]
  },
  {
   "title": "Coins With Highest Engagement (Upvotes & Comments)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT coin_name, \n       SUM(upvotes) AS total_upvotes, \n       SUM(num_comments) AS total_comments\nFROM reddit_posts\nWHERE coin_name is not null\nGROUP BY coin_name\nORDER BY total_upvotes DESC\nLIMIT 10;\n"
    },
    {}
   ]
  },
  {
   "title": "Top Coin Based on Popularity(Mentions)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT coin_name, \n       COUNT(*) AS mentions, \n       SUM(upvotes) AS total_upvotes, \n       AVG(CAST(json_extract_path_text(sentiment::json, 'score') AS FLOAT)) AS avg_sentiment\nFROM reddit_posts\nWHERE coin_name IS NOT NULL\nGROUP BY coin_name\nORDER BY mentions DESC;\n"
    }
   ]
  },
  {
   "title": "Most Active Subreddits for Meme Coins",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT subreddit, COUNT(*) AS post_count\nFROM reddit_posts\nGROUP BY subreddit\nORDER BY post_count DESC\nLIMIT 5;\n"
    },
    {}
   ]
  }
 ]
}